"""make phone_number nullable and add password_hash

Revision ID: c737bfc33872
Revises: bb8d022d2d64
Create Date: 2025-10-06 10:23:11.235088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c737bfc33872'
down_revision = 'bb8d022d2d64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role_assignments', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.drop_constraint('_user_role_uc', 'user_role_assignments', type_='unique')
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['aadhaar_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.drop_column('users', 'password_hash')
    op.create_unique_constraint('_user_role_uc', 'user_role_assignments', ['user_id', 'role_id'])
    op.drop_column('user_role_assignments', 'expires_at')
    # ### end Alembic commands ###