"""initial_migration

Revision ID: cd768c4bc5e9
Revises: 
Create Date: 2025-10-14 13:59:01.865670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd768c4bc5e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('otp_code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_email'), 'otp', ['email'], unique=False)
    op.create_index(op.f('ix_otp_phone_number'), 'otp', ['phone_number'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('permissions', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('uidai',
    sa.Column('aadhaar_number', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('phone_number', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('aadhaar_number')
    )
    op.create_index(op.f('ix_uidai_aadhaar_number'), 'uidai', ['aadhaar_number'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('mother_name', sa.String(), nullable=True),
    sa.Column('aadhaar_number', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('category', sa.Enum('SC', 'ST', 'OBC', 'GENERAL', 'OTHER', name='category'), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('PUBLIC', 'DISTRICT_AUTHORITY', 'SOCIAL_WELFARE', 'FINANCIAL_INSTITUTION', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=True),
    sa.Column('profile_image', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aadhaar_number'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_number', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('application_type', sa.Enum('PCR_RELIEF', 'POA_COMPENSATION', 'INTER_CASTE_MARRIAGE', 'OTHER', name='applicationtype'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'DOCUMENT_VERIFICATION_PENDING', 'APPROVED', 'DOCUMENTS_APPROVED', 'DISTRICT_AUTHORITY_REJECTED', 'DOCUMENTS_REJECTED', 'SOCIAL_WELFARE_APPROVED', 'SOCIAL_WELFARE_REJECTED', 'FI_REJECTED', 'REJECTED', 'FUND_DISBURSED', 'COMPLETED', name='applicationstatus'), nullable=True),
    sa.Column('incident_date', sa.DateTime(), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('incident_district', sa.String(), nullable=True),
    sa.Column('police_station', sa.String(), nullable=True),
    sa.Column('amount_approved', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('amount_disbursed', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bank_account_number', sa.String(), nullable=True),
    sa.Column('bank_ifsc_code', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('bank_branch', sa.String(), nullable=True),
    sa.Column('account_holder_name', sa.String(), nullable=True),
    sa.Column('fir_number', sa.String(), nullable=True),
    sa.Column('district_comments', sa.Text(), nullable=True),
    sa.Column('cctns_verified', sa.Boolean(), nullable=True),
    sa.Column('cctns_verification_date', sa.DateTime(), nullable=True),
    sa.Column('district_reviewed_by', sa.String(), nullable=True),
    sa.Column('district_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('social_welfare_comments', sa.Text(), nullable=True),
    sa.Column('social_welfare_reviewed_by', sa.String(), nullable=True),
    sa.Column('social_welfare_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('disbursed_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_number')
    )
    op.create_table('bank_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('ifsc_code', sa.String(), nullable=False),
    sa.Column('bank_name', sa.String(), nullable=False),
    sa.Column('branch_name', sa.String(), nullable=False),
    sa.Column('account_holder_name', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_steps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('step_name', sa.String(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('assigned_by', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_status_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('DISTRICT_AUTHORITY', 'SOCIAL_WELFARE', 'FINANCIAL_INSTITUTION', 'COMPLETED', name='applicationstage'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='stagestatus'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewer_role', sa.String(), nullable=True),
    sa.Column('stage_entered_at', sa.DateTime(), nullable=True),
    sa.Column('stage_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.Enum('AADHAAR_CARD', 'PAN_CARD', 'BIRTH_CERTIFICATE', 'BANK_PASSBOOK', 'CATEGORY_CERTIFICATE', 'INCOME_CERTIFICATE', 'MARRIAGE_CERTIFICATE', name='documenttype'), nullable=False),
    sa.Column('document_name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.String(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED', name='documentstatus'), nullable=True),
    sa.Column('is_digilocker', sa.Boolean(), nullable=True),
    sa.Column('digilocker_uri', sa.String(), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verified_by', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'document_type', name='uix_user_document_type')
    )
    op.create_index('idx_user_documents', 'documents', ['user_id', 'document_type'], unique=False)
    op.create_table('application_documents',
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_id', 'document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application_documents')
    op.drop_index('idx_user_documents', table_name='documents')
    op.drop_table('documents')
    op.drop_table('application_status_logs')
    op.drop_table('user_role_assignments')
    op.drop_table('onboarding_steps')
    op.drop_table('bank_accounts')
    op.drop_table('applications')
    op.drop_table('users')
    op.drop_index(op.f('ix_uidai_aadhaar_number'), table_name='uidai')
    op.drop_table('uidai')
    op.drop_table('roles')
    op.drop_index(op.f('ix_otp_phone_number'), table_name='otp')
    op.drop_index(op.f('ix_otp_email'), table_name='otp')
    op.drop_table('otp')
    # ### end Alembic commands ###